<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aDL_Moddeling_Project" nsURI="kit.sdq.aDL_Moddeling_Project"
    nsPrefix="aDL_Moddeling_Project">
  <eClassifiers xsi:type="ecore:EDataType" name="ExchangeInformation" instanceTypeName="ExchangeInformation"/>
  <eClassifiers xsi:type="ecore:EDataType" name="CommunicationManagementAddress" instanceTypeName="CommunicationManagementAddress"/>
  <eSubpackages name="ModularEnvironment" nsURI="kit.sdq.ModularEnvironment" nsPrefix="ModularEnvironment">
    <eClassifiers xsi:type="ecore:EClass" name="RuntimeFacility">
      <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
        <details key="archetype" value="Role"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="exchangeInformation"
          eType="#//ExchangeInformation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ManagementServiceEntity"
          lowerBound="1" upperBound="-1" eType="#//ModularEnvironment/ManagementServiceEntity"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="communicationmanagement"
          lowerBound="1" eType="#//ModularEnvironment/CommunicationManagement" eOpposite="#//ModularEnvironment/CommunicationManagement/servicemanagement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="session" upperBound="-1"
          eType="#//ModularEnvironment/Session" eOpposite="#//ModularEnvironment/Session/servicemanagement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ifacilityservices" eType="#//ModularEnvironment/IFacilityServices"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ManagementServiceEntity" eSuperTypes="#//ModularEnvironment/IManagementService">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ServiceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IManagementService" abstract="true"
        interface="true">
      <eOperations name="newOperation1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CommunicationManagement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Address" eType="#//CommunicationManagementAddress"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="servicemanagement" eType="#//ModularEnvironment/RuntimeFacility"
          eOpposite="#//ModularEnvironment/RuntimeFacility/communicationmanagement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="icommunication" lowerBound="1"
          upperBound="-1" eType="#//ModularEnvironment/ICommunication"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ICommunication" abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Session">
      <eStructuralFeatures xsi:type="ecore:EReference" name="servicemanagement" eType="#//ModularEnvironment/RuntimeFacility"
          eOpposite="#//ModularEnvironment/RuntimeFacility/session"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IFacilityServices" abstract="true"
        interface="true"/>
  </eSubpackages>
  <eSubpackages name="ModularSimulation" nsURI="kit.sdq.ModularSimulation" nsPrefix="ModularSimulation">
    <eClassifiers xsi:type="ecore:EClass" name="Federate">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="isimulation" eType="#//ModularSimulation/ISimulation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connectorfactory" lowerBound="1"
          eType="#//ModularSimulation/ConnectorFactory"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ISimulation" abstract="true" interface="true">
      <eOperations name="simulate"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConnectorFactory">
      <eOperations name="produce" eType="#//CommunicationManagementAddress"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="iproduce" lowerBound="1"
          upperBound="-1" eType="#//ModularSimulation/IProduce"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IProduce" abstract="true" interface="true">
      <eOperations name="produce" eType="#//CommunicationManagementAddress"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
