<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aDL_Moddeling_Project" nsURI="edu.kit.ipd.sdq.Modularization"
    nsPrefix="aDL_Moddeling_Project">
  <eSubpackages name="ModularEnvironment" nsURI="edu.kit.ipd.sdq.Modularization.ModularEnvironment"
      nsPrefix="ModularEnvironment">
    <eClassifiers xsi:type="ecore:EClass" name="MSEFacility" eSuperTypes="#//basic/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="managementservice" upperBound="-1"
          eType="#//ModularEnvironment/ManagementServices/ManagementService" containment="true"
          eOpposite="#//ModularEnvironment/ManagementServices/ManagementService/msefacility"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mseCouplingType" lowerBound="1"
          eType="#//ModularEnvironment/MSEType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mseserviceinterface"
          lowerBound="1" eType="#//ModularEnvironment/ManagementServices/MSEServiceInterface"
          containment="true" eOpposite="#//ModularEnvironment/ManagementServices/MSEServiceInterface/msefacility"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connector" lowerBound="1"
          upperBound="2" eType="#//Connectors/Connector" containment="true" eOpposite="#//Connectors/Connector/msefacility"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="MSEStandardTypes" eType="#//DataRepresentation/DataType"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="MSEStandardOperations"
          upperBound="-1" eType="#//DataRepresentation/Operation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="MSEType">
      <eLiterals name="Master"/>
      <eLiterals name="Worker" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Session" eSuperTypes="#//basic/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="SessionDataTypes" upperBound="-1"
          eType="#//DataRepresentation/DataType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ParticipantIDs" upperBound="-1"
          eType="#//basic/Identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operation" upperBound="-1"
          eType="#//DataRepresentation/Operation"/>
    </eClassifiers>
    <eSubpackages name="ManagementServices" nsURI="edu.kit.ipd.sdq.Modularization.ManagementServices"
        nsPrefix="ManagementServices">
      <eClassifiers xsi:type="ecore:EClass" name="ManagementService" eSuperTypes="#//basic/Entity">
        <eStructuralFeatures xsi:type="ecore:EReference" name="managementservice"
            upperBound="-1" eType="#//ModularEnvironment/ManagementServices/ManagementService"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="msefacility" eType="#//ModularEnvironment/MSEFacility"
            eOpposite="#//ModularEnvironment/MSEFacility/managementservice"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="managementservicefunctionality"
            lowerBound="1" eType="#//ModularEnvironment/ManagementServices/ManagementServiceFunctionality"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="managementservicesupportentity"
            upperBound="-1" eType="#//ModularEnvironment/ManagementServices/ManagementServiceSupportEntity"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ManagementServiceInterface" eSuperTypes="#//basic/Entity">
        <eStructuralFeatures xsi:type="ecore:EReference" name="servicefunctiondescription"
            upperBound="-1" eType="#//ModularEnvironment/ManagementServices/ServiceFunctionDescription"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="MSEServiceInterface">
        <eStructuralFeatures xsi:type="ecore:EReference" name="mseID" lowerBound="1"
            eType="#//basic/Identifier"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="managementservicefunctionality"
            upperBound="-1" eType="#//ModularEnvironment/ManagementServices/ManagementServiceFunctionality"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="msefacility" eType="#//ModularEnvironment/MSEFacility"
            eOpposite="#//ModularEnvironment/MSEFacility/mseserviceinterface"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ManagementServiceFunctionality"
          eSuperTypes="#//basic/Entity">
        <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingManagementServiceID"
            lowerBound="1" eType="#//basic/Identifier"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="managementserviceinterface"
            lowerBound="1" eType="#//ModularEnvironment/ManagementServices/ManagementServiceInterface"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ServiceFunctionDescription" eSuperTypes="#//basic/Entity">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="printableFunctionDescription"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="functionParameters"
            upperBound="-1" eType="#//DataRepresentation/stringToDataTypeMap" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ManagementServiceSupportEntity"
          eSuperTypes="#//basic/Entity"/>
      <eSubpackages name="AdapterServices" nsURI="edu.kit.ipd.sdq.Modularization.ManagementServices.AdapterServices"
          nsPrefix="AdapterServices">
        <eClassifiers xsi:type="ecore:EClass" name="DataMigrationAdapter" abstract="true"
            eSuperTypes="#//ModularEnvironment/ManagementServices/ManagementService">
          <eStructuralFeatures xsi:type="ecore:EReference" name="adaptationspecification"
              upperBound="-1" eType="#//ModularEnvironment/ManagementServices/AdapterServices/AdaptationSpecification"
              containment="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="SemanticAdapter" eSuperTypes="#//ModularEnvironment/ManagementServices/AdapterServices/DataMigrationAdapter"/>
        <eClassifiers xsi:type="ecore:EClass" name="DescriptiveAdapter" eSuperTypes="#//ModularEnvironment/ManagementServices/AdapterServices/DataMigrationAdapter"/>
        <eClassifiers xsi:type="ecore:EClass" name="StructuralAdapter" eSuperTypes="#//ModularEnvironment/ManagementServices/AdapterServices/DataMigrationAdapter"/>
        <eClassifiers xsi:type="ecore:EClass" name="ControlFlowAdapter" eSuperTypes="#//ModularEnvironment/ManagementServices/ManagementService"/>
        <eClassifiers xsi:type="ecore:EClass" name="TimeAdapter" eSuperTypes="#//ModularEnvironment/ManagementServices/ManagementService"/>
        <eClassifiers xsi:type="ecore:EClass" name="WorkloadAdapter" eSuperTypes="#//ModularEnvironment/ManagementServices/ManagementService"/>
        <eClassifiers xsi:type="ecore:EClass" name="AdaptationSpecification" abstract="true">
          <eStructuralFeatures xsi:type="ecore:EReference" name="fstSimID" lowerBound="1"
              eType="#//basic/Identifier"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="sndSimID" lowerBound="1"
              eType="#//basic/Identifier"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="DescriptiveAdaptSpecification">
          <eStructuralFeatures xsi:type="ecore:EReference" name="fstProperty" lowerBound="1"
              eType="#//basic/Identifier"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="sndProperty" eType="#//basic/Identifier"/>
        </eClassifiers>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="ModularSimulation" nsURI="edu.kit.ipd.sdq.Modularization.ModularSimulation"
      nsPrefix="ModularSimulation">
    <eClassifiers xsi:type="ecore:EClass" name="SimModule" eSuperTypes="#//basic/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="simmoduledescription"
          lowerBound="1" eType="#//ModularSimulation/SimModuleDescription" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connector" eType="#//Connectors/Connector"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mseserviceinterface"
          eType="#//ModularEnvironment/ManagementServices/MSEServiceInterface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SimModuleDescription" eSuperTypes="#//basic/Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="simulationDescription"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="distributeddatadescription"
          eType="#//DataRepresentation/DistributedDataDescription" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="AdaptationSpecs" upperBound="-1"
          eType="#//ModularEnvironment/ManagementServices/AdapterServices/AdaptationSpecification"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="basic" nsURI="edu.kit.ipd.sdq.Modularization.basic" nsPrefix="basic">
    <eClassifiers xsi:type="ecore:EClass" name="Identifier" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Entity" abstract="true" eSuperTypes="#//basic/Identifier #//basic/NamedElement"/>
  </eSubpackages>
  <eSubpackages name="Connectors" nsURI="edu.kit.ipd.sdq.Modularization.Connectors"
      nsPrefix="Connectors">
    <eClassifiers xsi:type="ecore:EClass" name="Connector" abstract="true" eSuperTypes="#//basic/Entity">
      <eOperations name="snd"/>
      <eOperations name="recv"/>
      <eOperations name="connect"/>
      <eOperations name="disconnect"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connection" upperBound="-1"
          eType="#//Connectors/Connection" containment="true" eOpposite="#//Connectors/Connection/connector"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="msefacility" eType="#//ModularEnvironment/MSEFacility"
          eOpposite="#//ModularEnvironment/MSEFacility/connector"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LocalConnector" eSuperTypes="#//Connectors/Connector"/>
    <eClassifiers xsi:type="ecore:EClass" name="RemoteConnector" eSuperTypes="#//Connectors/Connector">
      <eStructuralFeatures xsi:type="ecore:EReference" name="localAdress" lowerBound="1"
          eType="#//Connectors/DescriptiveAdress" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DescriptiveAdress">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="adress" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Connection" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="connector" eType="#//Connectors/Connector"
          eOpposite="#//Connectors/Connector/connection"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LocalConnection" eSuperTypes="#//Connectors/Connection">
      <eStructuralFeatures xsi:type="ecore:EReference" name="localconnector" lowerBound="1"
          eType="#//Connectors/LocalConnector"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RemoteConnection" eSuperTypes="#//Connectors/Connection">
      <eStructuralFeatures xsi:type="ecore:EReference" name="descriptiveadress" eType="#//Connectors/DescriptiveAdress"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="DataRepresentation" nsURI="edu.kit.ipd.sdq.Modularization.DataRepresentation"
      nsPrefix="DataRepresentation">
    <eClassifiers xsi:type="ecore:EClass" name="SemanticType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="semanticType" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="readableSemanticDescription"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DistributedDataDescription">
      <eStructuralFeatures xsi:type="ecore:EReference" name="publishObjectClasses"
          upperBound="-1" eType="#//DataRepresentation/ObjectClass" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subscriptions" upperBound="-1"
          eType="#//DataRepresentation/SubscribeData" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operation" upperBound="-1"
          eType="#//DataRepresentation/Operation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="UsageType">
      <eLiterals name="LocallyVisible" literal="LocallyVisible"/>
      <eLiterals name="GloballyVisible" value="1" literal="GloballyVisible"/>
      <eLiterals name="LocallyModifiable" value="2" literal="LocalModifiable"/>
      <eLiterals name="GloballyModifiable" value="3"/>
      <eLiterals name="NotPublished" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SubscribeType">
      <eLiterals name="Subscribe" value="1"/>
      <eLiterals name="SubscribeAndModify" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SubscribeData">
      <eStructuralFeatures xsi:type="ecore:EReference" name="semanticdatadescription"
          eType="#//DataRepresentation/SemanticType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="interaction" lowerBound="1"
          eType="#//DataRepresentation/SubscribeType" defaultValueLiteral="Subscribe"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subscriptionAttributeID"
          lowerBound="1" eType="#//basic/Identifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Unit" eSuperTypes="#//basic/Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseValueType" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="stepSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectClass" eSuperTypes="#//basic/Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="usageType" lowerBound="1"
          eType="#//DataRepresentation/UsageType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="property" upperBound="-1"
          eType="#//DataRepresentation/Property" containment="true" eOpposite="#//DataRepresentation/Property/objectclass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectclassoperation"
          upperBound="-1" eType="#//DataRepresentation/ObjectClassOperation" containment="true"
          eOpposite="#//DataRepresentation/ObjectClassOperation/objectclass"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//basic/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="semantictype" eType="#//DataRepresentation/SemanticType"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="usageType" eType="#//DataRepresentation/UsageType"
          defaultValueLiteral="LocallyVisible"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="singleValue" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="datatype" lowerBound="1"
          eType="#//DataRepresentation/DataType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectclass" eType="#//DataRepresentation/ObjectClass"
          eOpposite="#//DataRepresentation/ObjectClass/property"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="#//basic/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="unit" lowerBound="1"
          eType="#//DataRepresentation/Unit" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//basic/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//DataRepresentation/stringToDataTypeMap" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#//DataRepresentation/DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="stringToDataTypeMap" instanceClassName="java.util.Map$Entry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
          eType="#//DataRepresentation/DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectClassOperation" eSuperTypes="#//DataRepresentation/Operation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectclass" eType="#//DataRepresentation/ObjectClass"
          eOpposite="#//DataRepresentation/ObjectClass/objectclassoperation"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
